### ISSUE TITLE
【課題】 オリジナル機能実装_221009-221015

### ISSUE THREAD

**Issue by technicakidz** [dsuke0526/original-app#23]
### 課題

- 5 star rating の実装
- [x] `sandbox/` フォルダ等を作成し最小限構成で表示を確認する
   -  `.../sandbox/5starrating/index.html` ← この中で js をかくもOK
   - `.../sandbox/5starrating/style.css`
   - `.../sandbox/5starrating/hoge.js`
 - [x] アプリに組み込む(ブランチに注意)

**Comment by dsuke0526** [comment]
https://github.com/dsuke0526/original-app/tree/star-rating/blog
- ailed to load resource: the server responded with a status of 404 (Not Found)　star-rating.js:1
- Refused to execute script from 'http://127.0.0.1:8000/post/new/static/js/star-rating.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
というエラーメッセージがでました
二番目のエラーを調べたらhttps://teratail.com/questions/39021
を見つけのですが、回答の内容の「サーバの設定を変更し、外部scriptファイルが返す応答ヘッダに「Content-Type: text/javascript」が返されるように設定してください。」がよく分かりませんでした。

**Comment by technicakidz** [comment]
メモ

リモートブランチをとりこむ更新方法 (どのブランチでも実行できる)
```
git pull --rebase origin master
```
Django の web アプリモデルとは(MTVモデルの話)
https://farewell-work.hatenablog.com/entry/2017/05/07/160503

**Comment by technicakidz** [comment]
221015 追加分
下記を継続します．
> アプリに組み込む(ブランチに注意)

- post_edit のスタイル修正
- input タグ(star rating)の表示変化確認
- 他に Django テンプレートん乗っ取った書き方になっていないところはないか
- 質問ではスクリーンショット載せたりする

**Comment by dsuke0526** [comment]
![スクリーンショット (50)](https://user-images.githubusercontent.com/108209803/196616527-9aada7c7-0375-4e17-9c88-e650a0d76d1f.png)
https://github.com/dsuke0526/original-app/tree/5star-rating
成功しました。
あとはtopページに表示させかたの検討に入ろうと思います。
branchは新しく切った方になります。

**Comment by technicakidz** [comment]
やりましたね！課題としてはクリアですのでLGTMです！
5star-rating ブランチはこれからPRを作成される予定ですか？

**Comment by dsuke0526** [comment]
https://github.com/dsuke0526/original-app/pull/25
PR作成しました。

**Comment by technicakidz** [comment]
確認完了，LGTMです！
